"""
Mock data loader — reads pre-generated JSON from mock_data/ folder.

Why this exists: Development and CI environments don't have live API access.
USE_MOCK_DATA=true routes all integration calls through this loader instead of
hitting external APIs. The mock_data/ folder is generated by
scripts/generate_mock_data.py and committed to git.

Project root discovery: walks up from __file__ until a directory containing
.git/ is found. This avoids hardcoded absolute paths (CLAUDE.md Rule 1).
Override with MOCK_DATA_DIR env var for non-standard project layouts.
"""

from __future__ import annotations

import json
import logging
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

from src.models.ch.macro import MacroRow
from src.models.ch.ohlcv import OHLCVRow
from src.schemas.instruments import InstrumentResponse
from src.schemas.macro import (
    FRED_SERIES_NAMES,
    FRED_SERIES_UNITS,
    MacroBar,
    MacroSeriesResponse,
)
from src.schemas.market_data import QuoteResponse

logger = logging.getLogger(__name__)


class MockDataError(Exception):
    """Raised when mock data file is missing or contains malformed JSON."""


def _parse_dt(raw: str) -> datetime:
    """Parse ISO-8601 datetime string and ensure it is UTC-aware."""
    dt = datetime.fromisoformat(raw)
    if dt.tzinfo is None:
        return dt.replace(tzinfo=UTC)
    return dt


class MockDataLoader:
    """
    Reads pre-generated mock JSON files and returns internal schema types.

    All methods raise MockDataError when the expected file is absent —
    callers should treat this as a configuration error, not a data miss.

    Thread-safety: instances are read-only after construction; safe to share
    across async tasks without locking.
    """

    def __init__(self, mock_data_dir: Path) -> None:
        self._dir = mock_data_dir
        logger.info("MockDataLoader initialised — data dir: %s", mock_data_dir)

    # ------------------------------------------------------------------
    # Internal helpers
    # ------------------------------------------------------------------

    def _load_json(self, path: Path) -> Any:
        """Load and parse a JSON file. Raises MockDataError if absent."""
        if not path.exists():
            raise MockDataError(
                f"Mock data file not found: {path}. "
                "Run scripts/generate_mock_data.py to populate mock_data/."
            )
        return json.loads(path.read_text(encoding="utf-8"))

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def get_ohlcv(self, symbol: str, timeframe: str = "1D") -> list[OHLCVRow]:
        """
        Return OHLCV bars for *symbol* at *timeframe* resolution.

        Reads: mock_data/ohlcv/{SYMBOL}_{timeframe}.json
        Returns bars oldest-first, matching ClickHouse query order.
        """
        path = self._dir / "ohlcv" / f"{symbol}_{timeframe}.json"
        data = self._load_json(path)
        source: str = data.get("source", "mock")
        rows: list[OHLCVRow] = []
        for bar in data.get("bars", []):
            rows.append(
                OHLCVRow(
                    symbol=symbol,
                    timeframe=timeframe,
                    ts=_parse_dt(bar["ts"]),
                    open=float(bar["open"]),
                    high=float(bar["high"]),
                    low=float(bar["low"]),
                    close=float(bar["close"]),
                    volume=float(bar["volume"]),
                    source=source,
                    adj_close=(
                        float(bar["adj_close"])
                        if bar.get("adj_close") is not None
                        else None
                    ),
                )
            )
        return rows

    def get_macro_rows(self, series_id: str) -> list[MacroRow]:
        """
        Return raw MacroRow observations for *series_id* (ClickHouse insert shape).

        Reads: mock_data/macro/{series_id}.json
        Returns observations oldest-first. Returns [] for unknown series_id.
        """
        path = self._dir / "macro" / f"{series_id}.json"
        if not path.exists():
            logger.debug("No mock macro data found for series %s", series_id)
            return []
        data = self._load_json(path)
        source: str = data.get("source", "mock")
        return [
            MacroRow(
                series_id=series_id,
                ts=_parse_dt(b["ts"]),
                value=float(b["value"]),
                source=source,
            )
            for b in data.get("bars", [])
        ]

    def get_instruments(self) -> list[InstrumentResponse]:
        """
        Return all instruments from mock_data/instruments.json.

        The file is a JSON array of InstrumentResponse-shaped dicts.
        """
        path = self._dir / "instruments.json"
        data = self._load_json(path)
        return [InstrumentResponse(**item) for item in data]

    def get_quote(self, symbol: str) -> QuoteResponse | None:
        """
        Return the latest quote snapshot for *symbol*, or None if absent.

        Reads: mock_data/quotes.json (dict keyed by symbol).
        """
        path = self._dir / "quotes.json"
        data = self._load_json(path)
        entry: dict[str, object] | None = data.get(symbol)
        if entry is None:
            logger.debug("No mock quote found for symbol %s", symbol)
            return None
        return QuoteResponse(**entry)

    def get_macro_series(self, series_id: str) -> MacroSeriesResponse | None:
        """
        Return macro series observations in API response shape.

        Reads: mock_data/macro/{series_id}.json
        Returns None if the file is absent (unknown series_id).
        """
        path = self._dir / "macro" / f"{series_id}.json"
        if not path.exists():
            logger.debug("No mock macro data found for series %s", series_id)
            return None
        data = self._load_json(path)
        bars = [
            MacroBar(ts=_parse_dt(b["ts"]), value=float(b["value"]))
            for b in data.get("bars", [])
        ]
        return MacroSeriesResponse(
            series_id=series_id,
            name=FRED_SERIES_NAMES.get(series_id, series_id),
            unit=FRED_SERIES_UNITS.get(series_id, ""),
            bars=bars,
            source=data.get("source", "mock"),
        )
