"""
Mock data loader — reads pre-generated JSON from mock_data/ folder.

Why this exists: Development and CI environments don't have live API access.
USE_MOCK_DATA=true routes all integration calls through this loader instead of
hitting external APIs. The mock_data/ folder is generated by
scripts/generate_mock_data.py and committed to git.

Worker copy: returns only ClickHouse row types (OHLCVRow, MacroRow).
API Pydantic response schemas are not imported here — worker cannot depend
on api service (CLAUDE.md: no cross-service imports).

Project root discovery: walks up from __file__ until a directory containing
.git/ is found. This avoids hardcoded absolute paths (CLAUDE.md Rule 1).
Override with MOCK_DATA_DIR env var for non-standard project layouts.
"""

from __future__ import annotations

import json
import logging
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

from src.models.macro import MacroRow
from src.models.ohlcv import OHLCVRow

logger = logging.getLogger(__name__)


class MockDataError(Exception):
    """Raised when mock data file is missing or contains malformed JSON."""


def _parse_dt(raw: str) -> datetime:
    """Parse ISO-8601 datetime string and ensure it is UTC-aware."""
    dt = datetime.fromisoformat(raw)
    if dt.tzinfo is None:
        return dt.replace(tzinfo=UTC)
    return dt


class MockDataLoader:
    """
    Reads pre-generated mock JSON files and returns ClickHouse row types.

    All methods raise MockDataError when the expected file is absent —
    callers should treat this as a configuration error, not a data miss.

    Thread-safety: instances are read-only after construction; safe to share
    across async tasks without locking.
    """

    def __init__(self, mock_data_dir: Path) -> None:
        self._dir = mock_data_dir
        logger.info("MockDataLoader initialised — data dir: %s", mock_data_dir)

    # ------------------------------------------------------------------
    # Internal helpers
    # ------------------------------------------------------------------

    def _load_json(self, path: Path) -> Any:
        """Load and parse a JSON file. Raises MockDataError if absent."""
        if not path.exists():
            raise MockDataError(
                f"Mock data file not found: {path}. "
                "Run scripts/generate_mock_data.py to populate mock_data/."
            )
        return json.loads(path.read_text(encoding="utf-8"))

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def get_ohlcv(self, symbol: str, timeframe: str = "1D") -> list[OHLCVRow]:
        """
        Return OHLCV bars for *symbol* at *timeframe* resolution.

        Reads: mock_data/ohlcv/{SYMBOL}_{timeframe}.json
        Returns bars oldest-first, matching ClickHouse query order.
        """
        path = self._dir / "ohlcv" / f"{symbol}_{timeframe}.json"
        data = self._load_json(path)
        source: str = data.get("source", "mock")
        rows: list[OHLCVRow] = []
        for bar in data.get("bars", []):
            rows.append(
                OHLCVRow(
                    symbol=symbol,
                    timeframe=timeframe,
                    ts=_parse_dt(bar["ts"]),
                    open=float(bar["open"]),
                    high=float(bar["high"]),
                    low=float(bar["low"]),
                    close=float(bar["close"]),
                    volume=float(bar["volume"]),
                    source=source,
                    adj_close=(
                        float(bar["adj_close"])
                        if bar.get("adj_close") is not None
                        else None
                    ),
                )
            )
        return rows

    def get_macro_rows(self, series_id: str) -> list[MacroRow]:
        """
        Return raw MacroRow observations for *series_id* (ClickHouse insert shape).

        Reads: mock_data/macro/{series_id}.json
        Returns observations oldest-first.
        """
        path = self._dir / "macro" / f"{series_id}.json"
        if not path.exists():
            logger.debug("No mock macro data found for series %s", series_id)
            return []
        data = self._load_json(path)
        source: str = data.get("source", "mock")
        return [
            MacroRow(
                series_id=series_id,
                ts=_parse_dt(b["ts"]),
                value=float(b["value"]),
                source=source,
            )
            for b in data.get("bars", [])
        ]
